// <auto-generated />
using HumanResourcesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HumanResourcesAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221227093622_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("HumanResourcesAPI.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgeEmployee")
                        .HasColumnType("int");

                    b.Property<string>("EmailEmployee")
                        .HasColumnType("longtext");

                    b.Property<string>("LastNameEmployee")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NameEmployee")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK_Employee");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("HumanResourcesAPI.Entities.EmployeeFamiliar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgeEmployeeFamiliar")
                        .HasColumnType("int");

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<string>("LastNameEmployeeFamiliar")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NameEmployeeFamiliar")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK_EmployeeFamiliar");

                    b.HasIndex("IdEmployee");

                    b.ToTable("employee_familiar");
                });

            modelBuilder.Entity("HumanResourcesAPI.Entities.EmployeeFamiliar", b =>
                {
                    b.HasOne("HumanResourcesAPI.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("IdEmployee")
                        .HasConstraintName("FK_Employee_EmployeeFamiliar")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
